"""empty message

Revision ID: 3a65650e2e9d
Revises: 
Create Date: 2023-06-28 13:50:03.046094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a65650e2e9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_access_token',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户id'),
    sa.Column('user_name', sa.String(length=32), nullable=False, comment='用户名'),
    sa.Column('token', sa.String(length=40), nullable=False, comment='token'),
    sa.Column('perms', sa.String(length=1000), nullable=True, comment='权限集合'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    comment='Token'
    )
    op.create_table('t_role',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=32), nullable=False, comment='角色名称'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='角色'
    )
    op.create_table('t_user',
    sa.Column('user_name', sa.String(length=32), nullable=False, comment='用户名'),
    sa.Column('real_name', sa.String(length=32), nullable=False, comment='姓名'),
    sa.Column('password', sa.String(length=64), nullable=False, comment='密码'),
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name'),
    comment='用户'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_user')
    op.drop_table('t_role')
    op.drop_table('t_access_token')
    # ### end Alembic commands ###
