"""empty message

Revision ID: c77556256514
Revises: 3a65650e2e9d
Create Date: 2023-06-28 13:51:57.908665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77556256514'
down_revision = '3a65650e2e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_key', sa.String(length=32), nullable=False, comment='角色标识'))
        batch_op.create_unique_constraint(None, ['role_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('role_key')

    # ### end Alembic commands ###
